/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Renter;
import Home.*;
import Collect_Rent.*;

/**
 *
 * @author hp
 */
public class Renters extends javax.swing.JFrame {

    /**
     * Creates new form Renters
     */
    public Renters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cross_btn = new javax.swing.JLabel();
        CRent_btn1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upper_panel = new javax.swing.JLabel();
        Profit_btn_renters = new javax.swing.JLabel();
        property_btn1_renters = new javax.swing.JLabel();
        Renter_btn1_renters = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Add_Property = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Add_Property1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Add_Property2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Add_Property3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        cross_btn.setFont(new java.awt.Font("Tactic Round Bld", 0, 24)); // NOI18N
        cross_btn.setForeground(new java.awt.Color(255, 255, 255));
        cross_btn.setText("X");
        cross_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cross_btnMouseClicked(evt);
            }
        });
        getContentPane().add(cross_btn);
        cross_btn.setBounds(1320, 10, 17, 25);

        CRent_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Collect_Rent Btn.png"))); // NOI18N
        CRent_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CRent_btn1MouseClicked(evt);
            }
        });
        getContentPane().add(CRent_btn1);
        CRent_btn1.setBounds(10, 390, 250, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Renter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 20, 310, 70);

        upper_panel.setBackground(new java.awt.Color(51, 0, 51));
        upper_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upper panel.jpg"))); // NOI18N
        getContentPane().add(upper_panel);
        upper_panel.setBounds(260, 0, 1220, 120);

        Profit_btn_renters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profit Btn.png"))); // NOI18N
        getContentPane().add(Profit_btn_renters);
        Profit_btn_renters.setBounds(10, 500, 250, 80);

        property_btn1_renters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Property Btn.png"))); // NOI18N
        property_btn1_renters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                property_btn1_rentersMouseClicked(evt);
            }
        });
        getContentPane().add(property_btn1_renters);
        property_btn1_renters.setBounds(10, 180, 250, 80);

        Renter_btn1_renters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Renter Btn.png"))); // NOI18N
        getContentPane().add(Renter_btn1_renters);
        Renter_btn1_renters.setBounds(10, 280, 250, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Side Panel.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 265, 930);

        Add_Property.setIcon(new javax.swing.ImageIcon(getClass().getResource("/renter pic/add r.png"))); // NOI18N
        Add_Property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_PropertyMouseClicked(evt);
            }
        });
        getContentPane().add(Add_Property);
        Add_Property.setBounds(350, 300, 170, 170);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Add Renter");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 470, 110, 40);

        Add_Property1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/renter pic/search r.png"))); // NOI18N
        Add_Property1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Property1MouseClicked(evt);
            }
        });
        getContentPane().add(Add_Property1);
        Add_Property1.setBounds(620, 290, 170, 170);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Search Renter");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 460, 140, 40);

        Add_Property2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/renter pic/dlt rent.png"))); // NOI18N
        Add_Property2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Property2MouseClicked(evt);
            }
        });
        getContentPane().add(Add_Property2);
        Add_Property2.setBounds(890, 290, 170, 170);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Delete Renter");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(910, 460, 140, 40);

        Add_Property3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Show all Flat.png"))); // NOI18N
        Add_Property3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Property3MouseClicked(evt);
            }
        });
        getContentPane().add(Add_Property3);
        Add_Property3.setBounds(1160, 300, 170, 170);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Show All Renter");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1180, 470, 150, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void property_btn1_rentersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_property_btn1_rentersMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HomePage().setVisible(true);
        
    }//GEN-LAST:event_property_btn1_rentersMouseClicked

    private void Add_PropertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_PropertyMouseClicked

       new Add_renters().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_Add_PropertyMouseClicked

    private void Add_Property1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Property1MouseClicked
        // TODO add your handling code here:
         new Search_renters().setVisible(true);
        this.setVisible(false);
                              
    }//GEN-LAST:event_Add_Property1MouseClicked

    private void Add_Property2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Property2MouseClicked
        // TODO add your handling code here:
        
        new Delete_renters().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Add_Property2MouseClicked

    private void Add_Property3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Property3MouseClicked
        // TODO add your handling code here:
        
        new Show_renters().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Add_Property3MouseClicked

    private void CRent_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRent_btn1MouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        new Collect_Rent().setVisible(true);

    }//GEN-LAST:event_CRent_btn1MouseClicked

    private void cross_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cross_btnMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_cross_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Renters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Renters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Renters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Renters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Renters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Property;
    private javax.swing.JLabel Add_Property1;
    private javax.swing.JLabel Add_Property2;
    private javax.swing.JLabel Add_Property3;
    private javax.swing.JLabel CRent_btn1;
    private javax.swing.JLabel Profit_btn_renters;
    private javax.swing.JLabel Renter_btn1_renters;
    private javax.swing.JLabel cross_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel property_btn1_renters;
    private javax.swing.JLabel upper_panel;
    // End of variables declaration//GEN-END:variables
}
