package Home;


import java.awt.Toolkit;
import Property.*;
import Renter.*;
import Collect_Rent.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayon
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        
        
        initComponents();
        
       // Toolkit tk = Toolkit.getDefaultToolkit();
        //int xsize = (int) tk.getScreenSize().getWidth();
        //int ysize= (int) tk.getScreenSize().getHeight();
        
        //this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cross_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        upper_panel = new javax.swing.JLabel();
        Profit_btn = new javax.swing.JLabel();
        CRent_btn1 = new javax.swing.JLabel();
        property_btn1 = new javax.swing.JLabel();
        Renter_btn1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Search_Flat = new javax.swing.JLabel();
        Show_All_Flats = new javax.swing.JLabel();
        Delete_Flat = new javax.swing.JLabel();
        Add_Flat = new javax.swing.JLabel();
        Add_Property = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GeneralUser/logOut.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 670, 50, 50);

        cross_btn.setFont(new java.awt.Font("Tactic Round Bld", 0, 24)); // NOI18N
        cross_btn.setForeground(new java.awt.Color(255, 255, 255));
        cross_btn.setText("X");
        cross_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cross_btnMouseClicked(evt);
            }
        });
        jPanel2.add(cross_btn);
        cross_btn.setBounds(1320, 10, 17, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Property");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(670, 20, 310, 70);

        upper_panel.setBackground(new java.awt.Color(51, 0, 51));
        upper_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upper panel.jpg"))); // NOI18N
        jPanel2.add(upper_panel);
        upper_panel.setBounds(260, 0, 1220, 120);

        Profit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profit Btn.png"))); // NOI18N
        jPanel2.add(Profit_btn);
        Profit_btn.setBounds(10, 500, 250, 80);

        CRent_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Collect_Rent Btn.png"))); // NOI18N
        CRent_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CRent_btn1MouseClicked(evt);
            }
        });
        jPanel2.add(CRent_btn1);
        CRent_btn1.setBounds(10, 390, 250, 80);

        property_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Property Btn.png"))); // NOI18N
        jPanel2.add(property_btn1);
        property_btn1.setBounds(10, 180, 250, 80);

        Renter_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Renter Btn.png"))); // NOI18N
        Renter_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Renter_btn1MouseClicked(evt);
            }
        });
        jPanel2.add(Renter_btn1);
        Renter_btn1.setBounds(10, 280, 250, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Side Panel.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -20, 265, 930);

        Search_Flat.setBackground(new java.awt.Color(102, 255, 102));
        Search_Flat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search Flat.png"))); // NOI18N
        Search_Flat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_FlatMouseClicked(evt);
            }
        });
        jPanel2.add(Search_Flat);
        Search_Flat.setBounds(720, 460, 170, 170);

        Show_All_Flats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Show all Flat.png"))); // NOI18N
        Show_All_Flats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_All_FlatsMouseClicked(evt);
            }
        });
        jPanel2.add(Show_All_Flats);
        Show_All_Flats.setBounds(1100, 200, 170, 170);

        Delete_Flat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete Flat.png"))); // NOI18N
        Delete_Flat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_FlatMouseClicked(evt);
            }
        });
        jPanel2.add(Delete_Flat);
        Delete_Flat.setBounds(340, 460, 210, 170);

        Add_Flat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AddFlat.png"))); // NOI18N
        Add_Flat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_FlatMouseClicked(evt);
            }
        });
        jPanel2.add(Add_Flat);
        Add_Flat.setBounds(720, 200, 170, 170);

        Add_Property.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_Property.png"))); // NOI18N
        Add_Property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_PropertyMouseClicked(evt);
            }
        });
        jPanel2.add(Add_Property);
        Add_Property.setBounds(340, 190, 170, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Find Flat");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(770, 630, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Add Property");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(360, 360, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Add Flat");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(770, 370, 80, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Show All Flats");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(1120, 370, 130, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Delete Flat");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 630, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cross_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cross_btnMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_cross_btnMouseClicked

    private void Search_FlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_FlatMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        new SearchFlat().setVisible(true);
    }//GEN-LAST:event_Search_FlatMouseClicked

    private void Add_FlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_FlatMouseClicked
        this.setVisible(false);
        new AddFlat().setVisible(true);
    }//GEN-LAST:event_Add_FlatMouseClicked

    private void Show_All_FlatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_All_FlatsMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        new AllFlats().setVisible(true);
    }//GEN-LAST:event_Show_All_FlatsMouseClicked

    private void Delete_FlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_FlatMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteFlat().setVisible(true);
    }//GEN-LAST:event_Delete_FlatMouseClicked

    private void Add_PropertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_PropertyMouseClicked

        this.setVisible(false);
        new AddProperty().setVisible(true);
    }//GEN-LAST:event_Add_PropertyMouseClicked

    private void Renter_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Renter_btn1MouseClicked
        // TODO add your handling code here:
        
          this.setVisible(false);
        new Renters().setVisible(true);
        
        
    }//GEN-LAST:event_Renter_btn1MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
        this.setVisible(false);
        new SignIn().setVisible(true);
        
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void CRent_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRent_btn1MouseClicked
        // TODO add your handling code here:
        
         this.setVisible(false);
        new Collect_Rent().setVisible(true);
        
    }//GEN-LAST:event_CRent_btn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Flat;
    private javax.swing.JLabel Add_Property;
    private javax.swing.JLabel CRent_btn1;
    private javax.swing.JLabel Delete_Flat;
    private javax.swing.JLabel Profit_btn;
    private javax.swing.JLabel Renter_btn1;
    private javax.swing.JLabel Search_Flat;
    private javax.swing.JLabel Show_All_Flats;
    private javax.swing.JLabel cross_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel property_btn1;
    private javax.swing.JLabel upper_panel;
    // End of variables declaration//GEN-END:variables
}
