package Home;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayon
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SignIn_Btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SignUp_Email = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        SignUp_Password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SignUp_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SignIn_Btn1 = new javax.swing.JLabel();
        SignIn_Btn2 = new javax.swing.JLabel();
        SignIn_Btn3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SignIn_Btn4 = new javax.swing.JLabel();
        SignUp_Btn = new javax.swing.JLabel();
        SignUP_notice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tactic Round Bld", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        SignIn_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn.png"))); // NOI18N
        SignIn_Btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignIn_BtnMouseMoved(evt);
            }
        });
        SignIn_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignIn_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignIn_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignIn_BtnMouseExited(evt);
            }
        });
        jPanel1.add(SignIn_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 70));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 42)); // NOI18N
        jLabel1.setText("Create Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 340, 80));

        SignUp_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SignUp_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        SignUp_Email.setOpaque(false);
        SignUp_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(SignUp_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 360, 30));

        FirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        FirstName.setOpaque(false);
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 360, 30));

        LastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        LastName.setOpaque(false);
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        jPanel1.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 360, 30));

        SignUp_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        SignUp_Password.setOpaque(false);
        jPanel1.add(SignUp_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 360, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("User Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 80, -1));

        SignUp_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "General User" }));
        SignUp_combo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 255)));
        SignUp_combo.setOpaque(false);
        SignUp_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_comboActionPerformed(evt);
            }
        });
        jPanel1.add(SignUp_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("PassWord");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 80, -1));

        SignIn_Btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn.png"))); // NOI18N
        SignIn_Btn1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignIn_Btn1MouseMoved(evt);
            }
        });
        SignIn_Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignIn_Btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignIn_Btn1MouseExited(evt);
            }
        });
        jPanel1.add(SignIn_Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 70));

        SignIn_Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn.png"))); // NOI18N
        SignIn_Btn2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignIn_Btn2MouseMoved(evt);
            }
        });
        SignIn_Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignIn_Btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignIn_Btn2MouseExited(evt);
            }
        });
        jPanel1.add(SignIn_Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 70));

        SignIn_Btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn.png"))); // NOI18N
        SignIn_Btn3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignIn_Btn3MouseMoved(evt);
            }
        });
        SignIn_Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignIn_Btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignIn_Btn3MouseExited(evt);
            }
        });
        jPanel1.add(SignIn_Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 70));

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Signin Banner.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 620));

        SignIn_Btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn.png"))); // NOI18N
        SignIn_Btn4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignIn_Btn4MouseMoved(evt);
            }
        });
        SignIn_Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignIn_Btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignIn_Btn4MouseExited(evt);
            }
        });
        jPanel1.add(SignIn_Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 70));

        SignUp_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUp Btn.png"))); // NOI18N
        SignUp_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUp_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUp_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUp_BtnMouseExited(evt);
            }
        });
        jPanel1.add(SignUp_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 250, 70));
        jPanel1.add(SignUP_notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1068, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_EmailActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void SignUp_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_comboActionPerformed

    private void SignIn_BtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_BtnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_BtnMouseMoved

    private void SignIn_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_BtnMouseEntered
    SignIn_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn M.png"))); 
    }//GEN-LAST:event_SignIn_BtnMouseEntered

    private void SignIn_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_BtnMouseExited
        SignIn_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignIn Btn.png")));         // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_BtnMouseExited

    private void SignIn_Btn1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn1MouseMoved

    private void SignIn_Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn1MouseEntered

    private void SignIn_Btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn1MouseExited

    private void SignIn_Btn2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn2MouseMoved

    private void SignIn_Btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn2MouseEntered

    private void SignIn_Btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn2MouseExited

    private void SignIn_Btn3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn3MouseMoved

    private void SignIn_Btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn3MouseEntered

    private void SignIn_Btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn3MouseExited

    private void SignIn_Btn4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn4MouseMoved

    private void SignIn_Btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn4MouseEntered

    private void SignIn_Btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_Btn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_Btn4MouseExited

    private void SignUp_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_BtnMouseEntered
        SignUp_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUp Btn M.png")));
    }//GEN-LAST:event_SignUp_BtnMouseEntered

    private void SignUp_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_BtnMouseExited
        SignUp_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SignUp Btn.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_BtnMouseExited

    private void SignIn_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_BtnMouseClicked
        this.setVisible(false);
        new SignIn().setVisible(true);
        
    }//GEN-LAST:event_SignIn_BtnMouseClicked

    private void SignUp_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_BtnMouseClicked
       
       String First_Name= FirstName.getText();
       String Last_Name= LastName.getText();
       String Email= SignUp_Email.getText();
       String PassWord= SignUp_Password.getText();
       String User_Type= (String) SignUp_combo.getSelectedItem();
       
       
       if(User_Type.equalsIgnoreCase("Admin")){
       if(First_Name.isEmpty() || Last_Name.isEmpty() || Email.isEmpty() || PassWord.isEmpty() ){
       
       SignUP_notice.setText("Please verify all fields");
       }
       else
       {
           AdminRegistration reg = new AdminRegistration();
           reg.adRegister(First_Name, Last_Name, Email, PassWord);
           SignUP_notice.setText("Registered Successfully");
           FirstName.setText("");
           LastName.setText("");
           SignUp_Email.setText("");
           
           
       }
    }
       else
       {
           //System.out.println("Failed!!");
            if(First_Name.isEmpty() || Last_Name.isEmpty() || Email.isEmpty() || PassWord.isEmpty() ){
       
       SignUP_notice.setText("Please verify all fields");
       }
       else
       {
           AdminRegistration reg = new AdminRegistration();
           reg.GURegister(First_Name, Last_Name, Email, PassWord);
           SignUP_notice.setText("Registered Successfully");
           FirstName.setText("");
           LastName.setText("");
           SignUp_Email.setText("");
           
           
       }
           
           
       }
       
      
   
       
       
      
       
       
       
       
       
        
        
        
    }//GEN-LAST:event_SignUp_BtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel SignIn_Btn;
    private javax.swing.JLabel SignIn_Btn1;
    private javax.swing.JLabel SignIn_Btn2;
    private javax.swing.JLabel SignIn_Btn3;
    private javax.swing.JLabel SignIn_Btn4;
    private javax.swing.JLabel SignUP_notice;
    private javax.swing.JLabel SignUp_Btn;
    private javax.swing.JTextField SignUp_Email;
    private javax.swing.JPasswordField SignUp_Password;
    private javax.swing.JComboBox<String> SignUp_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
