/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Property;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Home.*;
import java.awt.List;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;



/**
 *
 * @author Ayon
 */
public class AddFlat extends javax.swing.JFrame {
     String selectbuildingf;
     //String building[];

    /**
     * Creates new form Building
     */
    public AddFlat() {
        
        
        
        initComponents();
        
  
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cross_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        upper_panel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Total_Room = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        select_building = new javax.swing.JComboBox<>();
        Add_flat = new javax.swing.JLabel();
        Rent_Fee = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("<Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 620, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add FLat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 340, 190, 70);

        cross_btn.setFont(new java.awt.Font("Tactic Round Bld", 0, 24)); // NOI18N
        cross_btn.setForeground(new java.awt.Color(255, 255, 255));
        cross_btn.setText("X");
        cross_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cross_btnMouseClicked(evt);
            }
        });
        jPanel1.add(cross_btn);
        cross_btn.setBounds(1320, 10, 17, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Property");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 20, 310, 70);

        upper_panel.setBackground(new java.awt.Color(51, 0, 51));
        upper_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upper panel.jpg"))); // NOI18N
        jPanel1.add(upper_panel);
        upper_panel.setBounds(260, 0, 1220, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Side Panel.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 265, 930);

        Total_Room.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Total_Room.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        Total_Room.setOpaque(false);
        Total_Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_RoomActionPerformed(evt);
            }
        });
        jPanel1.add(Total_Room);
        Total_Room.setBounds(610, 240, 350, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Total Room");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(610, 210, 100, 17);

        select_building.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select_building.setForeground(new java.awt.Color(0, 102, 102));
        select_building.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Building 1", "Building 2", "Building 3", "Building 4", "Building 5" }));
        select_building.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buildingActionPerformed(evt);
            }
        });
        jPanel1.add(select_building);
        select_building.setBounds(610, 430, 140, 30);

        Add_flat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ADD.png"))); // NOI18N
        Add_flat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_flatMouseClicked(evt);
            }
        });
        jPanel1.add(Add_flat);
        Add_flat.setBounds(640, 550, 260, 90);

        Rent_Fee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_Fee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        Rent_Fee.setOpaque(false);
        Rent_Fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_FeeActionPerformed(evt);
            }
        });
        jPanel1.add(Rent_Fee);
        Rent_Fee.setBounds(610, 340, 350, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Rent Fee");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 310, 100, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cross_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cross_btnMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_cross_btnMouseClicked

    private void Total_RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_RoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_RoomActionPerformed

    private void select_buildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buildingActionPerformed
        // TODO add your handling code here:
        
       
               
               
    }//GEN-LAST:event_select_buildingActionPerformed

    private void Add_flatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_flatMouseClicked
        // TODO add your handling code here:
        
        String TotalRoom = Total_Room.getText();
        int TotalRoomInt =Integer.parseInt(TotalRoom);
        
        String RentFee = Rent_Fee.getText();
        int RentFeeInt =Integer.parseInt(RentFee);
        
        String Building_Name= (String) select_building.getSelectedItem();
        
        
        
               try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
            "jdbc:sqlserver://localhost:1433;databaseName=ApartmentBusinessManagement;selectMethod=cursor", "sa", "123456");



String sql = "Insert into FLAT"
                    +"(BuildingName,TotalRooms,RentFee)"
                    +"values(?,?,?)";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, Building_Name);
            pst.setInt(2, TotalRoomInt);
            pst.setInt(3,RentFeeInt);
           
            
            
            
            
           
          
            pst.executeUpdate();
            
           new shortMessage().setVisible(true);
           
           Total_Room.setText("");
           Rent_Fee.setText("");
            
           
            
           
            
            
            


            


} catch (Exception e) {
    e.printStackTrace();
}
        
        
        
        
       


    }//GEN-LAST:event_Add_flatMouseClicked

    private void Rent_FeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_FeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_FeeActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        new HomePage().setVisible(true);
        
        
        
        
        

    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
         ArrayList<String> building = new ArrayList<String>(); 
         
               try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
            "jdbc:sqlserver://localhost:1433;databaseName=ApartmentBusinessManagement;selectMethod=cursor", "sa", "123456");





            String sql = "Select BuildingName from PROPERTY";
                        PreparedStatement pst = connection.prepareStatement(sql);
                        
                        
                        ResultSet rs = pst.executeQuery();
                        
                        ResultSetMetaData rsmetadata = rs.getMetaData();
                        int columns = rsmetadata.getColumnCount();
                        
                        
                        
            while (rs.next()) {
                building.add(rs.getString("BuildingName"));
               
            }
                        


                     


} catch (Exception e) {
    e.printStackTrace();
}
               String[] strArr = new String[building.size()];
               building.toArray(strArr);
               
               DefaultComboBoxModel mod = new DefaultComboBoxModel(strArr);
               select_building.setModel(mod);
               
               
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_flat;
    private javax.swing.JTextField Rent_Fee;
    private javax.swing.JTextField Total_Room;
    private javax.swing.JLabel cross_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> select_building;
    private javax.swing.JLabel upper_panel;
    // End of variables declaration//GEN-END:variables
}
