/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Property;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Home.*;
/**
 *
 * @author Ayon
 */
public class AddProperty extends javax.swing.JFrame {

    /**
     * Creates new form AddProperty
     */
    public AddProperty() {
        this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Add_p_notice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cross_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        upper_panel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Building_Area = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Building_Name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Building_Cost = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Building_Flat_Number = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("<Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 660, 180, 40);

        Add_p_notice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add_p_notice.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(Add_p_notice);
        Add_p_notice.setBounds(590, 640, 270, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Property");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 380, 180, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 340, 110, 70);

        cross_btn.setFont(new java.awt.Font("Tactic Round Bld", 0, 24)); // NOI18N
        cross_btn.setForeground(new java.awt.Color(255, 255, 255));
        cross_btn.setText("X");
        cross_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cross_btnMouseClicked(evt);
            }
        });
        jPanel1.add(cross_btn);
        cross_btn.setBounds(1320, 10, 17, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Property");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 20, 310, 70);

        upper_panel.setBackground(new java.awt.Color(51, 0, 51));
        upper_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upper panel.jpg"))); // NOI18N
        jPanel1.add(upper_panel);
        upper_panel.setBounds(260, 0, 1220, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Side Panel.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 265, 930);

        Building_Area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Building_Area.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        Building_Area.setOpaque(false);
        Building_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Building_AreaActionPerformed(evt);
            }
        });
        jPanel1.add(Building_Area);
        Building_Area.setBounds(560, 290, 350, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Area");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 260, 100, 17);

        Building_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Building_Name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        Building_Name.setOpaque(false);
        Building_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Building_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Building_Name);
        Building_Name.setBounds(560, 200, 350, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Building Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 180, 100, 17);

        Building_Cost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Building_Cost.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        Building_Cost.setOpaque(false);
        Building_Cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Building_CostActionPerformed(evt);
            }
        });
        jPanel1.add(Building_Cost);
        Building_Cost.setBounds(560, 380, 350, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Initial Cost");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(560, 350, 100, 17);

        Building_Flat_Number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Building_Flat_Number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 204, 204)));
        Building_Flat_Number.setOpaque(false);
        Building_Flat_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Building_Flat_NumberActionPerformed(evt);
            }
        });
        jPanel1.add(Building_Flat_Number);
        Building_Flat_Number.setBounds(560, 480, 350, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Total Flat");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(560, 450, 100, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ADD.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(600, 550, 320, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cross_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cross_btnMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_cross_btnMouseClicked

    private void Building_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Building_AreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Building_AreaActionPerformed

    private void Building_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Building_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Building_NameActionPerformed

    private void Building_CostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Building_CostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Building_CostActionPerformed

    private void Building_Flat_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Building_Flat_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Building_Flat_NumberActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        
       String BuildingName= Building_Name.getText();
       String BuildingArea= Building_Area.getText();
       String BuildingCost= Building_Cost.getText();
       int BuildingCostInt =Integer.parseInt(BuildingCost);
       String BuildingFlat_Number= Building_Flat_Number.getText();
       int BuildingFlat_NumberInt =Integer.parseInt(BuildingFlat_Number);
       
       
       
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
            "jdbc:sqlserver://localhost:1433;databaseName=ApartmentBusinessManagement;selectMethod=cursor", "sa", "123456");



String sql = "Insert into PROPERTY"
                    +"(BuildingName,Area,initialcost,TotalFlats)"
                    +"values(?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, BuildingName);
            pst.setString(2, BuildingArea);
            pst.setInt(3,BuildingCostInt);
            pst.setInt(4,BuildingFlat_NumberInt);
            
            
            
            
           
          
            pst.executeUpdate();
            
           Building_Name.setText("");
           Building_Area.setText("");
           Building_Cost.setText("");
           Building_Flat_Number.setText("");
           Add_p_notice.setText("Property Added Successfully");
           
            
            
            


            


} catch (Exception e) {
    e.printStackTrace();
}
       
       
       
       
       
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        new HomePage().setVisible(true);

    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProperty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_p_notice;
    private javax.swing.JTextField Building_Area;
    private javax.swing.JTextField Building_Cost;
    private javax.swing.JTextField Building_Flat_Number;
    private javax.swing.JTextField Building_Name;
    private javax.swing.JLabel cross_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel upper_panel;
    // End of variables declaration//GEN-END:variables
}
